/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Symbol */
            symbol: string;
            /**
             * Period
             * @default 3mo
             */
            period: string;
            /**
             * Asset Type
             * @default stock
             */
            asset_type: string;
            /**
             * Risk Profile
             * @default moderate
             */
            risk_profile: string;
            /** Options Strategy */
            options_strategy?: string | null;
            /** Options Legs */
            options_legs?: components["schemas"]["OptionsLegRequest"][] | null;
            /**
             * Dte
             * @description Days to expiration
             */
            dte?: number | null;
            /**
             * Net Premium
             * @description Net credit (+) or debit (−) per share
             */
            net_premium?: number | null;
            /**
             * Premium Sign
             * @description +1 credit strategy, -1 debit strategy
             */
            premium_sign?: number | null;
            /** Spot Low */
            spot_low?: number | null;
            /** Spot High */
            spot_high?: number | null;
            /** Position Qty */
            position_qty?: number | null;
            /** Position Entry */
            position_entry?: number | null;
            /**
             * Position Side
             * @default long
             */
            position_side: string;
            /** Position Lots */
            position_lots?: components["schemas"]["PositionLot"][] | null;
            /**
             * Cost Basis Method
             * @default average
             * @enum {string}
             */
            cost_basis_method: "fifo" | "lifo" | "average" | "specific";
            /**
             * Include Dividends
             * @default false
             */
            include_dividends: boolean;
            /**
             * Adjust For Splits
             * @default true
             */
            adjust_for_splits: boolean;
        };
        /** FibLevel */
        FibLevel: {
            /** Name */
            name: string;
            /** Price */
            price: number;
            /** Distance Pct */
            distance_pct: number;
            /** Strength */
            strength: string;
            /** Type */
            type: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HoldFoldVerdict */
        HoldFoldVerdict: {
            /** Symbol */
            symbol: string;
            /** Asset Type */
            asset_type: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "HOLD EM" | "FOLD EM" | "NEUTRAL";
            /** Confidence */
            confidence: number;
            /** Price */
            price: number;
            /** Bias */
            bias: string;
            /** Risk Level */
            risk_level: string;
            /** Cached */
            cached: boolean;
            /** Bullish Count */
            bullish_count: number;
            /** Bearish Count */
            bearish_count: number;
            /** Avg Score */
            avg_score: number;
            /** Top Signals */
            top_signals: {
                [key: string]: unknown;
            }[];
            /** Rsi */
            rsi: number | null;
            /** Macd */
            macd: number | null;
            /** Adx */
            adx: number | null;
            /** Atr */
            atr: number | null;
            /** Volatility Regime */
            volatility_regime: string;
            /** Volume Spike */
            volume_spike: string | null;
            /** Suppressions */
            suppressions: components["schemas"]["SuppressionInfo"][];
            /** Trade Timeframe */
            trade_timeframe: string | null;
            /** Entry */
            entry: number | null;
            /** Stop */
            stop: number | null;
            /** Target */
            target: number | null;
            /** Risk Reward */
            risk_reward: number | null;
            /** Stop Pct */
            stop_pct: number | null;
            /** Upside Pct */
            upside_pct: number | null;
            /** Vehicle */
            vehicle: string | null;
            /** Vehicle Notes */
            vehicle_notes: string | null;
            /** Primary Signal */
            primary_signal: string | null;
            /** Supporting Signals */
            supporting_signals: string[];
            /** Position Qty */
            position_qty: number | null;
            /** Position Entry */
            position_entry: number | null;
            /** Position Side */
            position_side: string;
            /** Position Pnl Pct */
            position_pnl_pct: number | null;
            /** Position Pnl Dollar */
            position_pnl_dollar: number | null;
            /** Position Vs Stop */
            position_vs_stop: string | null;
            /** Position Vs Target */
            position_vs_target: string | null;
            position_aging?: components["schemas"]["PositionAging"] | null;
            position_pnl_detail?: components["schemas"]["PositionPnL"] | null;
            /** Fib Levels */
            fib_levels: components["schemas"]["FibLevel"][];
            /** Fib Confluence Zones */
            fib_confluence_zones: {
                [key: string]: unknown;
            }[];
            /** Nearest Fib Support */
            nearest_fib_support: number | null;
            /** Nearest Fib Resistance */
            nearest_fib_resistance: number | null;
            options_greeks: components["schemas"]["OptionsGreeks"] | null;
            /** Options Strategy */
            options_strategy: string | null;
            /** Options Legs */
            options_legs: components["schemas"]["OptionsLegResponse"][] | null;
            /** Dte */
            dte: number | null;
            /** Net Premium */
            net_premium: number | null;
            /** Max Profit */
            max_profit: number | null;
            /** Max Loss */
            max_loss: number | null;
            /** Spread Width */
            spread_width: number | null;
            /** Breakeven Prices */
            breakeven_prices: number[] | null;
            /** Pop */
            pop: number | null;
            /** Payoff Curve */
            payoff_curve: components["schemas"]["PayoffPoint"][] | null;
            /** Strategy Note */
            strategy_note: string | null;
            /** Summary */
            summary: string;
            /** Data Timestamp */
            data_timestamp: string | null;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Warnings */
            warnings?: string[];
            /** Request Id */
            request_id?: string | null;
            /**
             * Disclaimer Version
             * @default 1.0
             */
            disclaimer_version: string;
        };
        /** LotPnL */
        LotPnL: {
            /** Lot Id */
            lot_id: string | null;
            /** Qty */
            qty: number;
            /** Cost Basis Effective */
            cost_basis_effective: number;
            /** Acquired At */
            acquired_at: string | null;
            /** Side */
            side: string;
            /** Unrealized Dollar */
            unrealized_dollar: number;
            /** Unrealized Pct */
            unrealized_pct: number;
        };
        /** OptionsGreeks */
        OptionsGreeks: {
            /** Iv */
            iv: number | null;
            /** Pcr */
            pcr: number | null;
            /** Delta Atm */
            delta_atm: number | null;
            /** Theta Atm */
            theta_atm: number | null;
            /** Vega Atm */
            vega_atm: number | null;
        };
        /** OptionsLegRequest */
        OptionsLegRequest: {
            /** Role */
            role: string;
            /** Strike */
            strike?: number | null;
            /** Expiry */
            expiry?: string | null;
            /** Premium */
            premium?: number | null;
        };
        /** OptionsLegResponse */
        OptionsLegResponse: {
            /** Role */
            role: string;
            /** Strike */
            strike: number | null;
            /** Expiry */
            expiry: string | null;
            /** Premium */
            premium?: number | null;
        };
        /** PayoffPoint */
        PayoffPoint: {
            /** Price */
            price: number;
            /** Pnl */
            pnl: number;
        };
        /** PositionAging */
        PositionAging: {
            /** Earliest Acquired */
            earliest_acquired: string;
            /** Weighted Avg Age Days */
            weighted_avg_age_days: number;
            /** Long Term Pct */
            long_term_pct: number;
            /** Short Term Pct */
            short_term_pct: number;
        };
        /**
         * PositionLot
         * @description A single tax lot within a position.
         */
        PositionLot: {
            /** Qty */
            qty: number;
            /** Cost Basis */
            cost_basis: number;
            /** Acquired At */
            acquired_at?: string | null;
            /**
             * Side
             * @default long
             * @enum {string}
             */
            side: "long" | "short";
            /** Fees Total */
            fees_total?: number | null;
            /** Account Type */
            account_type?: ("taxable" | "ira" | "roth" | "401k" | "margin" | "cash") | null;
            /** Lot Id */
            lot_id?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** PositionPnL */
        PositionPnL: {
            /** Unrealized Dollar */
            unrealized_dollar: number;
            /** Unrealized Pct */
            unrealized_pct: number;
            /** Realized Dollar */
            realized_dollar: number;
            /** Fees Paid Total */
            fees_paid_total: number;
            /** Dividends Received */
            dividends_received: number | null;
            /** Split Adjustments Applied */
            split_adjustments_applied: number;
            /** Cost Basis Effective */
            cost_basis_effective: number;
            /** Cost Basis Method */
            cost_basis_method: string;
            /** Breakdown By Lot */
            breakdown_by_lot: components["schemas"]["LotPnL"][] | null;
        };
        /** SuppressionInfo */
        SuppressionInfo: {
            /** Code */
            code: string;
            /** Label */
            label: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldFoldVerdict"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
